[versions]
kotlin = "2.1.10"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:5.0.3"
kotlinxCollectionsImmutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.8"
lsp4j = "org.eclipse.lsp4j:org.eclipse.lsp4j:0.24.0"

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
